server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: document-management-service
          uri: lb:http://DOCUMENT-MANAGEMENT-SERVICE
          predicates:
            - Path=/dms/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/