server:
  port: 9222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: document-management-service
          uri: lb:http://DOCUMENT-MANAGEMENT-SERVICE
          predicates:
            - Path=/dms/**
        - id: product-management-service
          uri: lb:http://PRODUCT-MANAGEMENT-SERVICE
          predicates:
            - Path=/product-management/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9762/eureka/