server:
  port: 9801

spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/keycloak-app

  data:
    mongodb:
      uri: mongodb://localhost:27017/document-management-service

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9762/eureka/

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest