spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/keycloak-app

  application:
    name: notification-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification-management-service
    username: postgres
    password: cdac
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: liquivista@gmail.com
    password: sbps xhvq vpnw tgba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9804

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9762/eureka/

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue:
    json:
      name: first_success_queue
  exchange:
    name: first_success_exchange
  routing:
    key: first_success_routing_key

  response:
    queue:
      name: response_queue
    exchange:
      name: response_exchange
    routing:
      key: response_routing_key
